# ==============================
# = SPRING APPLICATION CONFIG =
# ==============================
spring.application.name=processor-store
server.port=8080

# ==============================
# = DATABASE CONFIG =
# ==============================
spring.datasource.url=jdbc:h2:mem:processors_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==============================
# = JPA / HIBERNATE CONFIG =
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================
# = STATIC RESOURCES =
# ==============================
# Everything inside src/main/resources/static will be served automatically.
spring.web.resources.static-locations=classpath:/static/

# ==============================
# = LOGGING =
# ==============================
logging.level.org.springframework=INFO
logging.level.com.example.store=DEBUG

# ==============================
# = ACTIVE PROFILE =
# ==============================
spring.profiles.active=dev

#external services
exchange.api-key=
exchange.base-url=https://v6.exchangerate-api.com/v6